2020-02-06T12:48:11.1303136+01:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-02-06T12:48:11.1476318+01:00  [INF] Hosting environment: "Development" (c3307c92)
2020-02-06T12:48:11.1477251+01:00  [INF] Content root path: "C:\Users\benaz\Documents\asp-core\WebTest\WebTest" (b5d60022)
2020-02-06T12:48:11.3575638+01:00 80000037-0000-fe00-b63f-84710c7967bb [ERR] erreur (81c911ae)
2020-02-06T12:53:58.1689820+01:00  [FTL] Application startup exception (6c57a5ba)
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'WebTest.Middlewares.ErrorLoggingMiddleware'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
2020-02-06T12:58:22.3058734+01:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-02-06T12:58:22.3180186+01:00  [INF] Hosting environment: "Development" (c3307c92)
2020-02-06T12:58:22.3181362+01:00  [INF] Content root path: "C:\Users\benaz\Documents\asp-core\WebTest\WebTest" (b5d60022)
2020-02-06T12:58:22.4223984+01:00 80000021-0001-fc00-b63f-84710c7967bb [ERR] erreur (81c911ae)
2020-02-06T12:59:18.8447707+01:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-02-06T12:59:18.8531533+01:00  [INF] Hosting environment: "Development" (c3307c92)
2020-02-06T12:59:18.8532500+01:00  [INF] Content root path: "C:\Users\benaz\Documents\asp-core\WebTest\WebTest" (b5d60022)
2020-02-06T12:59:24.0923317+01:00 80000014-0000-fd00-b63f-84710c7967bb [ERR] The following error happened: test (b696e6fe)
2020-02-06T12:59:24.8294002+01:00 80000014-0000-fd00-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.Exception: test
   at WebTest.Controllers.HomeController.Index() in C:\Users\benaz\Documents\asp-core\WebTest\WebTest\Controllers\HomeController.cs:line 27
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at WebTest.Middlewares.ErrorLoggingMiddleware.Invoke(HttpContext context) in C:\Users\benaz\Documents\asp-core\WebTest\WebTest\Middlewares\ErrorLoggingMiddleware.cs:line 24
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
